enable-module-update = true
parallel-jobs = 1



[YouTube]
patches-source = "anddea/revanced-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
app-name = "YouTube"
build-mode = "both"#both means packing both apk and module at the same time. To pack only mask module, change both to module
version = "auto"#Remember to check the patch support version before each package
rv-brand = "ReVanced Extended"
#Remember to change these two versions when the patch is updated
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Custom branding name for YouTube'"#Exclusion list
included-patches = "'Custom header for YouTube'"#Mandatory inclusion list Patches have a default list, some are disabled by default
patcher-args = " -e 'MaterialYou' -e 'Return YouTube Username' -e'Custom branding icon for YouTube' -OappIcon='mmt_turquoise' -OchangeSplashIcon='true' -OrestoreOldSplashAnimation='true' -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon='yt_alt' -OapplyToAll='true' -e 'Custom header for YouTube' -OcustomHeader='custom_branding_icon' -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -e 'Settings for YouTube' -OrvxSettingsLabel='Revanced Extended' -OinsertPosition=@string/about_key"
